spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bitbucket_bot
    username: postgres
    driver-class-name: org.postgresql.Driver
    password:
  liquibase:
    change-log: classpath:liquibase/change-log.xml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  config: classpath:logback-prod.xml
bitbucketbot:
  scheduler:
    person: 0 0 0 */1 * *
    comment:
      settings:
        no-comment-count: 20
        comment-count: 100
  init:
    start-comment-id: 7807
    use: false
  bitbucket:
    token: ${BITBUCKET_ADMIN_TOKEN}
    url-pull-request-open: http://localhost:7990/rest/api/1.0/dashboard/pull-requests?limit=150&state=OPEN
    url-pull-request-close: http://localhost:7990/rest/api/1.0/dashboard/pull-requests?limit=150&closedSince=86400
    url-pull-request-comment: http://localhost:7990/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/comments/{commentId}
    url-pull-request: http://localhost:7990/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/overview
    url-users: http://localhost:7990/rest/api/1.0/admin/users
  teamcity:
    token: ${TEAMCITY_ADMIN_TOKEN}
    project-url: http://localhost:8111/app/rest/projects
    build-url: http://localhost:8111/app/rest/builds/?locator=project:(id:{0}),branch:(default:any)